name: Pulumi Preview Test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
